### ISSUE TITLE
SyntaxError: Unexpected token >

### ISSUE THREAD

**Issue by puven12** [denysdovhan/learnyoubash#40]
I just installed the learnyoubash workshop. And getting  this error in Ubuntu 14.04.4. Nodejs version : v0.10.25

/usr/local/lib/node_modules/learnyoubash/utils/problem.js:6
module.exports = (dirname, getArgs) => {
                                     ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/learnyoubash/exercises/hello_world/exercise.js:1:80)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

**Comment by denysdovhan** [comment]
@puven12 hey! Thank you for reaching out!

Sorry for late answer! I was especially busy these days :(

Yeah, that behavior is OK. You've run this workshopper on old and unsupported version of Node.js. This workshopper uses the latest features from ES2015, like arrow-function. Try to upgrade your Node.js version to the latest one and issue will disappear 😉 

I'm going to close this issue. Feel free to reopen if you have something to ask.
