### ISSUE TITLE
"run" command throws an error but "verify" works fine

### ISSUE THREAD

**Issue by richardpringle** [denysdovhan/learnyoubash#53]
```
Could not run: TypeError: Incorrect value of args option
    at normalizeSpawnArguments (child_process.js:314:11)
    at exports.spawn (child_process.js:372:38)
    at Promise (/usr/local/lib/node_modules/learnyoubash/utils/execute.js:6:16)
    at module.exports (/usr/local/lib/node_modules/learnyoubash/utils/execute.js:3:36)
    at Object.run (/usr/local/lib/node_modules/learnyoubash/utils/problem.js:61:12)
    at WA.executeExercise (/usr/local/lib/node_modules/learnyoubash/node_modules/workshopper-adventure/index.js:425:16)
    at WA.process (/usr/local/lib/node_modules/learnyoubash/node_modules/workshopper-adventure/index.js:317:17)
    at WA.run (/usr/local/lib/node_modules/learnyoubash/node_modules/workshopper-adventure/index.js:262:15)
    at Object.exports.handler (/usr/local/lib/node_modules/learnyoubash/node_modules/workshopper-adventure/lib/commands/run.js:12:21)
    at method.valid.$ (/usr/local/lib/node_modules/learnyoubash/node_modules/commandico/commandico.js:143:15)
```

I'm on node 7.10.1

**Comment by richardpringle** [comment]
after debugging, it looks like the value of `args` is the number 2 instead of an array

**Comment by richardpringle** [comment]
(I get this with **parameters** and **arrays** exercises, not the ones before this)

**Comment by denysdovhan** [comment]
Huge thanks for reporting! Sorry for waiting so long. Just fixed and will be published in the next release.

**Comment by richardpringle** [comment]
:+1:
